# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 21:45
from __future__ import unicode_literals

import ciclotour.routes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waypoint',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=17, validators=[ciclotour.routes.validators.validate_latitude]),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=18, validators=[ciclotour.routes.validators.validate_longitude]),
        ),
    ]
