# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-30 11:19
from __future__ import unicode_literals

import ciclotour.routes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_polyline'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=50, unique=True)),
                ('icon', models.ImageField(max_length=255, upload_to=ciclotour.routes.models._pointkind_icon_directory_path)),
            ],
        ),
    ]
