# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-01 08:49
from __future__ import unicode_literals

import ciclotour.routes.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_pointkind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=17, validators=[ciclotour.routes.validators.validate_latitude])),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=18, validators=[ciclotour.routes.validators.validate_longitude])),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.PointKind')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.Route')),
            ],
        ),
    ]
