# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-07 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_routepicture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routepicture',
            options={'ordering': ['-id']},
        ),
    ]
