# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-08 17:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_auto_20160507_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
