# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-08 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0008_route_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
