# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-08 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0009_auto_20160508_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['-created']},
        ),
    ]
