# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-29 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0012_set_final_waypoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='shared_with',
            field=models.CharField(choices=[('PV', 'Privada'), ('PB', 'Pública'), ('FO', 'Com amigos')], default='PB', max_length=2),
        ),
    ]
