# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-17 00:31
from __future__ import unicode_literals

import ciclotour.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=ciclotour.core.models._user_profile_directory_path),
        ),
    ]
