# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-07 09:25
from __future__ import unicode_literals

import ciclotour.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160417_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationToken',
            fields=[
                ('token', models.CharField(blank=True, default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('expire_date', models.DateTimeField(default=ciclotour.core.models._now_plus_7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
