# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-08 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_confirmationtoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'usuário', 'verbose_name_plural': 'usuários'},
        ),
    ]
