# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-12 02:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0014_routecomment'),
        ('core', '0006_auto_20160530_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CO', 'Comentou')], max_length=2)),
                ('target', models.CharField(choices=[('RT', 'Rota'), ('PT', 'Ponto')], max_length=2)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('route_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='routes.RouteComment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
