# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-12 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_useractivity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('CO', 'comentou')], max_length=2),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='target',
            field=models.CharField(choices=[('RT', 'a rota'), ('PT', 'o ponto')], max_length=2),
        ),
    ]
