# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-12 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0015_pointcomment'),
        ('core', '0008_auto_20160612_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='point_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='routes.PointComment'),
        ),
    ]
